### PR TITLE
rework the way cfgs are handled

### LINKED ISSUE #137: Constants cannot be cfg-gated multiple times

### LINKED ISSUE #198: Support allow non_upper_case_globals lint.
I'm trying to create a bitflags with CamelCase naming. However adding #[allow(non_upper_case_globals)] everywhere doesn't suppress the lints.

### LINKED ISSUE #215: Debug formatting leads to less desireable output
[Link to rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%23%5Bmacro_use%5D%0Aextern%20crate%20bitflags%3B%0A%0Abitflags!%20%7B%0A%20%20%20%20struct%20Flags%3A%20u32%20%7B%0A%20%20%20%20%20%20%20%20const%20A%20%3D%200b00000001%3B%0A%20%20%20%20%20%20%20%20const%20B%20%3D%200b00000010%3B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%200b00000100%3B%0A%20%20%20%20%20%20%20%20const%20ABC%20%3D%20Self%3A%3AA.bits%20%7C%20Self%3A%3AB.bits%20%7C%20Self%3A%3AC.bits%3B%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20Flags%3A%3AA%20%7C%20Flags%3A%3AB%20%7C%20Flags%3A%3AC%20)%3B%0A%7D)

```rust
#[macro_use]
extern crate bitflags;

bitflags! {
    struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
        const C = 0b00000100;
        const ABC = Self::A.bits | Self::B.bits | Self::C.bits;
    }
}

fn main() {
    println!("{:?}", Flags::A | Flags::B | Flags::C );
}
```

prints:

```bash
A | B | C | ABC
```

I find it somewhat less helpful that both the expanded (`A | B | C`) and "compressed" form (`ABC`) are reported...

Is there a reason behind this? Is this considered more correct for some reason?

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #137 
Closes #198 
Closes #215 

The current approach for handling `#[cfg]`'d flags is to define a trait that includes all names unconditionally, and then only set them to values based on actual `#[cfg]`'s. Unfortunately this means we can't support redefining flags (they'd appear twice in the unconditional list). This approach simplifies things by defining an internal `Bits` trait that captures the operations we require of primitive bits types. We now define `all` as `from_bits_truncate` with all bits set.

### CODE REVIEW

**Comment by KodrAus** [comment]
Getting back to having a single macro that defines bitflags types should make it much easier for us to do #264 properly. After that I think we're just about ready for the next major release (the first with the `BitFlags` trait).

**Comment by hillin** [comment]
When is this change going to be released?

**Comment by hillin** [comment]
@KodrAus Is there a plan to release with this feature?

**Pull request merged**
