### PR TITLE
Add example to the README.md file

### PR DESCRIPTION
**Pull request by tiaanl**
Add a simple example to the README.md file to show the capabilities of the crate.  The README is displayed in many places where developers are evaluating its use and having an example is always useful.

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks @tiaanl! This looks good to me, but for the README it might be good to put some comments inline with the `bitflags!` invocation and its use to suggest the macro is how you define a flags type, which then generates a bunch of set-like methods for you. What do you think?

**Comment by tiaanl** [comment]
@KodrAus I copied a small comment from the `lib.rs` docs and also grabbed the example code from there to add more use cases.

**Review by KodrAus — APPROVED** [review]
Thanks @tiaanl! Sorry for the radio silence on this one. This looks good to me.

**Comment by tiaanl** [comment]
@KodrAus Thanks for the approval.  I'm not sure why all the checks are failing.  I only changed the README 😕 Any suggestions?

**Comment by KodrAus** [comment]
That's just changes to Rust's compiler messages so nothing to worry about here. I've fixed those up so will merge this one in. Thanks again!

**Pull request merged**
