### PR TITLE
Allows empty flag definition

### LINKED ISSUE #179: Empty bitflags definitions fail to parse
This doesn't parse:

```rust
bitflags::bitflags! {
    pub struct BoxFlags: u8 {
    }
}
```

### PR DESCRIPTION
**Pull request by thiagoarrais**
Fixes #179

Please keep in mind I'm kind of a Rust newbie and even more of a Rust _macro_ newbie. I'm not sure this is more convoluted than necessary.

### CODE REVIEW

**Comment by thiagoarrais** [comment]
CI failures seem unrelated as they also happen on the main branch.

Maybe #216 fixes them?

**Comment by KodrAus** [comment]
Thanks @thiagoarrais! Would you like to try rebasing on the current `master` and see if we end up in a green state again?

**Comment by thiagoarrais** [comment]
Rebased and we're back to green.

**Comment by thiagoarrais** [comment]
Hey, @KodrAus, any blockers here?

**Comment by KodrAus** [comment]
Thanks for pushing through this @thiagoarrais. I had a bit of a break from things but am taking a look through now. It looks like we've ended up with another conflict, so I'll take a look through here to save you the trouble and get this in 🙇

**Pull request merged**
